### ISSUE TITLE
Add REST endpoints for CRUD operations

### ISSUE THREAD

**Issue by JacobTheEvans** [HamburgChimps/gorilla-auth#13]
### Result
All queries and mutations will have corresponding REST endpoint that can be used as an alternative to graphQL

### Implantation
Use a graphql client inside of a express-router endpoints that serve as a proxy for graphql

**Comment by chopmann** [comment]
I dont know if this is required.
I think we only need to provide some non graphql endpoints.
/../login POST ---> return token
/../authorize POST --> return {allowed: true}

**Comment by JacobTheEvans** [comment]
I defiantly dont think is was required but it would make more gorilla accessible. I love graphQL but some users still may want to use REST.

**Comment by JacobTheEvans** [comment]
Solved by inclusion of Plugins feature
